"""Generate offline KMP dictionary data from the supplied portal XML snapshots."""
from pathlib import Path
import json
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parents[1]
files = dict(currency="currencyList.xml", unit="unitList.xml", region="regionList.xml",
             vat="ndsList.xml", okei="okeiList.xml", country="oksmList.xml",
             package="packageList.xml", category="categoryList.xml")
out = root / "composeApp/src/commonMain/kotlin/ru/ymlstudio/DictionaryData.kt"
lines = ["// Generated by tools/build_dictionaries.py. Do not edit manually.", "package ru.ymlstudio", "", "internal object DictionaryData {"]
for key, filename in files.items():
    entries = list(ET.parse(root / "dictionaries" / filename).getroot())
    rows = []
    for e in entries:
        rows.append("\t".join(e.get(k, "").replace("\t", " ").replace("\n", " ").replace("\r", " ")
                              for k in ("id", "code", "name", "parentId")) + "\n")
    chunks, current = [], ""
    for row in rows:
        if len((current + row).encode("utf-8")) > 24000:
            chunks.append(current)
            current = ""
        current += row
    if current:
        chunks.append(current)
    lines.append(f"    val `{key}`: String by lazy {{ listOf(")
    lines.extend("        " + json.dumps(c, ensure_ascii=False).replace("$", "\\$") + "," for c in chunks)
    lines.append('    ).joinToString("") }')
    print(key, len(entries))
lines.append("}")
out.write_text("\n".join(lines) + "\n")
